[build]
command = "npm run-script build"
publish = "dist"


[[Redirects]]
from = "http://muralidharan.me/home"
  to = "https://muralidharan.me/index.html"
  status = 301

[[Redirects]]
from = "https://muralidharan.me/home"
  to = "https://muralidharan.me/index.html"
  status = 301

[[Redirects]]
from = "www.muralidharan.me/home"
  to = "https://muralidharan.me/index.html"
  status = 301

[[plugins]]
package = "netlify-plugin-no-more-404"

  # all inputs are optional, we just show you the defaults below
  [plugins.inputs]

  # either "warn" or "error"
  on404 = "error"

  # change this key to a new one any time you need to restart from scratch
  cacheKey = "MyCacheKey"

  # (for development) turn true for extra diagnostic logging
  debugMode = false
