[build]
command = "npm run-script build"
publish = "dist"


[[Redirects]]
from = "http://muralidharan.me/home"
  to = "https://muralidharan.me/index.html"
  status = 301

[[Redirects]]
from = "https://muralidharan.me/home"
  to = "https://muralidharan.me/index.html"
  status = 301

[[Redirects]]
from = "www.muralidharan.me/home"
  to = "https://muralidharan.me/index.html"
  status = 301
